# Generated by Django 4.2.19 on 2025-02-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='stock_count',
            new_name='piece',
        ),
    ]
